### PR TITLE
Fix a bug.

### PR DESCRIPTION
**Pull request by Phemon**
Fix a bug.

### CODE REVIEW

**Comment by Menci** [comment]
😕 Fix a bug.
😋 Fix a XXX bug on YYY conditions.

**Comment by Menci** [comment]
It seems that you are fixing a security issue which provide access to the whole web server disk with testdata download APIs. But I can't reproduce it.

```

**Comment by Menci** [comment]
Thanks~

**Comment by Phemon** [comment]
> Thanks~

I don't want  people with bad purpose to see this bug so I didn't write the details in the title.  
Replace '/' with "%2F" is useful.

**Pull request merged**
